### ISSUE TITLE
Doesn't wanna Bypass for Melonloader

### ISSUE THREAD

**Issue by ForsakenWaRp** [Cr4nkSt4r/PhasBypass#1]
Trying this with multiple Injectors
Issue i'm getting without Melonloader it hooks and works but when i try it with Melonloader it auto closes? 
is this my Injection Delay or?

**Comment by Cr4nkSt4r** [comment]
# Copied from [here](https://github.com/Cr4nkSt4r/phasmophobia-melon-mod/issues/11)

I'm using **v0.4.3 Open-Beta**
The download stuff is something they added to prevent it from working with phas.
They are reading the json from [ML api](https://api.melonloader.com/api/v1/game/phasmophobia)
and just manipulating the return values in a way, which MelonLoader does not like.
Can be easily circumvented.

As second measurement, they are checking, if the game is phasmophobia, before they even get to the download and the Bootstrapper will just close itself, so MelonLoader does not even gets loaded.


Just download their latest sourcecode and make changes to the Bootstrap project and the Il2CppAssemblyGenerator one.

[Bootstrap](https://prnt.sc/1s3f216)
[Il2CppAssemblyGenerator](https://prnt.sc/1s3f4fo)

Il2CppAssemblyGenerator can be circumvented in many ways, I personally choosed another simpler way, but this will work too.

_Originally posted by @Cr4nkSt4r in https://github.com/Cr4nkSt4r/phasmophobia-melon-mod/issues/11#issuecomment-922137982_

**Comment by ForsakenWaRp** [comment]
Thanks worked like a charm didn't see the issue <3

**Comment by Cr4nkSt4r** [comment]
It was a issue on the Mod GitHub page, that's why I copied the text from there, so we can have a issue with the same topic on this repo :)

I'm glad it worked.

**Comment by orcun9988** [comment]
what exactly should we change in bootstrap so that the visual one-on-one is the same?

> # Copied from [here](https://github.com/Cr4nkSt4r/phasmophobia-melon-mod/issues/11)
> I'm using **v0.4.3 Open-Beta** The download stuff is something they added to prevent it from working with phas. They are reading the json from [ML api](https://api.melonloader.com/api/v1/game/phasmophobia) and just manipulating the return values in a way, which MelonLoader does not like. Can be easily circumvented.
> 
> As second measurement, they are checking, if the game is phasmophobia, before they even get to the download and the Bootstrapper will just close itself, so MelonLoader does not even gets loaded.
> 
> Just download their latest sourcecode and make changes to the Bootstrap project and the Il2CppAssemblyGenerator one.
> 
> [Bootstrap](https://prnt.sc/1s3f216) [Il2CppAssemblyGenerator](https://prnt.sc/1s3f4fo)
> 
> Il2CppAssemblyGenerator can be circumvented in many ways, I personally choosed another simpler way, but this will work too.
> 
> _Originally posted by @Cr4nkSt4r in https://github.com/Cr4nkSt4r/phasmophobia-melon-mod/issues/11#issuecomment-922137982_
> 
> # Second
> The injection can happen, as long as the game has the loading screen, injection after that point can be to late.
