### ISSUE TITLE
working??

### ISSUE THREAD

**Issue by cassell1337** [Cr4nkSt4r/PhasBypass#11]
is this still working as when i replace the bootstrap with it, it doesnt wanna open game i could be using wrong im not sure there is no text saying how to use it

**Comment by cassell1337** [comment]
[Cr:4n:kS.t4r] [C4PhasByP] !!! ONLY FOR !!! Server version: VR Overhaul | Hotfix v0.6.1.7
[Cr:4n:kS.t4r] [C4PhasByP] !!! ONLY FOR !!! Steam Build ID: 8629104
[Cr:4n:kS.t4r] [C4PhasByP] Creating Hooks!

all i get is this then closes

**Comment by Cr4nkSt4r** [comment]
Check against the BuildID from SteamDB.
It does work for the BuildID provided.
If you need help, check the closed issues.
