### ISSUE TITLE
problem when compile

### ISSUE THREAD

**Issue by daniiGP** [Cr4nkSt4r/PhasBypass#12]
Hello, my problem is that when I try to compile the code I get this: The application on which this project type is based was not found.
I know it's a very stupid problem but I'm new and I want to try to solve it, could someone help me?
![image](https://user-images.githubusercontent.com/96537843/172406837-690d5ea5-6e8f-4762-8e62-1ad49e85f3bc.png)

**Comment by daniiGP** [comment]
no, I just realized, I have installed it and it already compiles, thank you very much

**Comment by Cr4nkSt4r** [comment]
Great to hear.
Thanks for letting me know.
