### ISSUE TITLE
updated bypass for todays update

### ISSUE THREAD

**Issue by TheRealBalto** [Cr4nkSt4r/PhasBypass#2]
have you already created it and im just dumb? or are you still working on it? I havent seen anything in the discord

**Comment by TheRealBalto** [comment]
Ive tried everything that I know of and keeps crashing at start up

**Comment by Cr4nkSt4r** [comment]
**It was updated two times today:**

Update: To support BuildID 7382984 …
Cr4nkSt4r committed 4 hours ago

Update: To support BuildID 7379698 …
Cr4nkSt4r committed 8 hours ago
