### ISSUE TITLE
Crashing when injecting

### ISSUE THREAD

**Issue by MatthewJack65** [Cr4nkSt4r/PhasBypass#5]
Basically the title, the game crashes when injecting the dll. 

**The only logs on the file bypass_log.txt:**

```
[Cr:4n:kS.t4r] [C4PhasByP] !!! ONLY FOR !!! Server version: 0.4.1.0 - Nightmare Balance Hotfix
[Cr:4n:kS.t4r] [C4PhasByP] !!! ONLY FOR !!! Steam Build ID: 7645974
[Cr:4n:kS.t4r] [C4PhasByP] Creating Hooks!
```

**Comment by Cr4nkSt4r** [comment]
You answered your problem with your own picture.
Why do you mean I've implemented these messages?
Outdated bypass = crash.

**Comment by MatthewJack65** [comment]
It is not outdated, I compiled the dll 1 day after the last update

**Comment by Cr4nkSt4r** [comment]
> It is not outdated, I compiled the dll 1 day after the last update

And why do you lie?
**Nov 4, 2021:** Updated to _Server version: 0.4.1.1_
**Nov 5, 2021 (your issue post and log):** _Server version: 0.4.1.0_

**Comment by MatthewJack65** [comment]
Well,

First, I was not lying
Second, I maybe fucked up something when compiling
