### ISSUE TITLE
Release builds

### ISSUE THREAD

**Issue by niansa** [Cr4nkSt4r/PhasBypass#7]
Hey, since I don't have access to MSVC, I'd like to see release builds ;-)

**Comment by MrMasrozYTLIVE** [comment]
eh if anyone only know how to do it LOL

**Comment by Cr4nkSt4r** [comment]
This is linked on UC, so binaries or links to them, aren't allowed, so they'll never be included here.

**Comment by niansa** [comment]
What is UC?

**Comment by Cr4nkSt4r** [comment]
> What is UC?
Unknowncheats
