### ISSUE TITLE
about ghost can't kill you

### ISSUE THREAD

**Issue by orcun9988** [Cr4nkSt4r/PhasBypass#8]
main.cpp line: 164
`	//DetourAttach(&(PVOID&)__403____________, DoNothingMethod); `

I change like this and then ghost can kill me 
will this cause any damage to the file?

**Comment by Cr4nkSt4r** [comment]
When they moved some functions around over the 2nd half of 2021, could be another function now.
Maybe they even removed the original function at that address
Never really played with the bypass, just started the and a game for testing.
So prob. the local kill player event, but removing this, shouldn't harm in any way.

**Comment by Cr4nkSt4r** [comment]
Removed with commit 8229cf9
